### ISSUE TITLE
when will support GO and Rust?

### ISSUE THREAD

**Issue by yxxhero** [OmriGM/code-metrics#1]
this is great tool. I hope that can support Go and Rust. thanks so much. thanks for your Project.

**Comment by OmriGM** [comment]
Hey @yxxhero 
I'll add Go and Rust support to my roadmap as high priority task.

Thank you for the suggestion and feedback 👍🏻

**Comment by OmriGM** [comment]
Hey @yxxhero , I just released [version 0.0.7](https://marketplace.visualstudio.com/items?itemName=OmriGrossman.live-code-metric) which adds support for both Go, Rust, and also PHP. Could you try it out and confirm it works as expected for you? 
Thank you :)

**Comment by yxxhero** [comment]
@OmriGM cool. thanks so much.
