### ISSUE TITLE
JSX Files error

### ISSUE THREAD

**Issue by GiovanniJMDev** [OmriGM/code-metrics#3]
With JSX files it does not recognize the name of the functions, but when you change the same file to js it recognizes them perfectly. Otherwise it works great.

**Comment by OmriGM** [comment]
Hey @GiovanniJMDev, thanks for bringing this up. 
I'll add to to my roadmap, thanks for the feedback 🙏🏻

**Comment by OmriGM** [comment]
Glad it worked out for you, closing this issue 👍🏻
